### PR TITLE
Introduce peek() method, for direct, non-mutable output buffer access

### PR DESCRIPTION
**Pull request by tk70**
This is the use case:

```rust
use common_lib::synth_info_block::{OscillatorInfoBlock, SynthInfoBlock};
use triple_buffer::Output;

pub struct SynthStateView {
    rx: Output<SynthInfoBlock>,
}

impl SynthStateView {
    pub fn new(rx: Output<SynthInfoBlock>) -> Self {
        Self { rx }
    }

    // Get the latest data from the triple buffer. Note that this may not be the most recent data. Fetch should be called first.
    pub fn get(&self) -> &SynthInfoBlock {
        //     ^^^^^
        // self.rx.output_buffer()
        //     ^^^^^^^^^^^^^
        self.rx.peek()
    }

    // Update the output of the triple buffer. Should be called before trying to obtain the latest data.
    pub fn fetch(&mut self) {
        self.rx.update();
    }

    #[inline]
    pub fn oscillators(&self) -> Option<&OscillatorInfoBlock> {
        self.get().oscillators.as_ref()
    }

    #[inline]
    pub fn osc_allocated(&self) -> usize {
        self.oscillators().map_or(0, |osc| osc.n_allocated)
    }

    #[inline]
    pub fn total_osc(&self) -> usize {
        self.oscillators().map_or(0, |osc| osc.osc_total)
    }

    #[inline]
    pub fn last_cc_used(&self) -> u8 {
        self.get().control.last_cc_used
    }
}
```

### CODE REVIEW

**Review by HadrienG2 — CHANGES_REQUESTED** [review]
Thanks for the contribution! In hindsight, what I should have done is to provide a pair of `output_buffer()`/`output_buffer_mut()` methods, following the usual convention. But I don't think it's worth doing a breaking change to fix.

Would you mind picking a name which highlights a bit more that the two methods are heavily related, though? Something like `peek_output_buffer()` would be just fine.

**Comment by tk70** [comment]
updated the commit

**Review by HadrienG2 — APPROVED** [review]
Thanks for your time and contribution again!

**Comment by HadrienG2** [comment]
This change has been published at v8 (which is semver-major due to the change in MSRV that happened since the last release).

**Comment by tk70** [comment]
Kindly consider applying the "correct" naming convention when releasing v8.

**Comment by HadrienG2** [comment]
Too late, it's already published. Adding an issue for it as something for the next major release ;) But it would probably be nicer to existing library users anyway if I started with some deprecation period where `output_buffer()` throws a warning about the planned semantics change.

**Pull request merged**
